package artem.balan.telegrambotcurrencyexchangerate.types;

import lombok.AllArgsConstructor;
import lombok.Getter;

@SuppressWarnings("unused")
@AllArgsConstructor
public enum CurrencyAbbreviationsTypes {
    FJD("Fijian Dollar"),
    MXN("Mexican Peso"),
    STD("São Tomé and Príncipe Dobra (pre-2018)"),
    SCR("Seychellois Rupee"),
    CDF("Congolese Franc"),
    BBD("Barbadian Dollar"),
    GTQ("Guatemalan Quetzal"),
    CLP("Chilean Peso"),
    HNL("Honduran Lempira"),
    UGX("Ugandan Shilling"),
    ZAR("South African Rand"),
    TND("Tunisian Dinar"),
    STN("São Tomé and Príncipe Dobra"),
    CUC("Cuban Convertible Peso"),
    BSD("Bahamian Dollar"),
    SLL("Sierra Leonean Leone"),
    SDG("Sudanese Pound"),
    IQD("Iraqi Dinar"),
    CUP("Cuban Peso"),
    GMD("Gambian Dalasi"),
    TWD("New Taiwan Dollar"),
    RSD("Serbian Dinar"),
    DOP("Dominican Peso"),
    KMF("Comorian Franc"),
    MYR("Malaysian Ringgit"),
    FKP("Falkland Islands Pound"),
    XOF("CFA Franc BCEAO"),
    GEL("Georgian Lari"),
    BTC("Bitcoin"),
    UYU("Uruguayan Peso"),
    MAD("Moroccan Dirham"),
    CVE("Cape Verdean Escudo"),
    TOP("Tongan Pa'anga"),
    AZN("Azerbaijani Manat"),
    OMR("Omani Rial"),
    PGK("Papua New Guinean Kina"),
    KES("Kenyan Shilling"),
    SEK("Swedish Krona"),
    CNH("Chinese Yuan (Offshore)"),
    BTN("Bhutanese Ngultrum"),
    UAH("Ukrainian Hryvnia"),
    GNF("Guinean Franc"),
    ERN("Eritrean Nakfa"),
    MZN("Mozambican Metical"),
    SVC("Salvadoran Colón"),
    ARS("Argentine Peso"),
    QAR("Qatari Rial"),
    IRR("Iranian Rial"),
    XPD("Palladium Ounce"),
    CNY("Chinese Yuan"),
    THB("Thai Baht"),
    UZS("Uzbekistan Som"),
    XPF("CFP Franc"),
    MRU("Mauritanian Ouguiya"),
    BDT("Bangladeshi Taka"),
    LYD("Libyan Dinar"),
    BMD("Bermudan Dollar"),
    KWD("Kuwaiti Dinar"),
    PHP("Philippine Peso"),
    XPT("Platinum Ounce"),
    RUB("Russian Ruble"),
    PYG("Paraguayan Guarani"),
    ISK("Icelandic Króna"),
    JMD("Jamaican Dollar"),
    COP("Colombian Peso"),
    MKD("Macedonian Denar"),
    USD("United States Dollar"),
    DZD("Algerian Dinar"),
    PAB("Panamanian Balboa"),
    GGP("Guernsey Pound"),
    SGD("Singapore Dollar"),
    ETB("Ethiopian Birr"),
    JEP("Jersey Pound"),
    KGS("Kyrgystani Som"),
    SOS("Somali Shilling"),
    VEF("Venezuelan Bolívar Fuerte (Old)"),
    VUV("Vanuatu Vatu"),
    LAK("Laotian Kip"),
    BND("Brunei Dollar"),
    XAF("CFA Franc BEAC"),
    LRD("Liberian Dollar"),
    XAG("Silver Ounce"),
    CHF("Swiss Franc"),
    HRK("Croatian Kuna"),
    ALL("Albanian Lek"),
    DJF("Djiboutian Franc"),
    VES("Venezuelan Bolívar Soberano"),
    ZMW("Zambian Kwacha"),
    TZS("Tanzanian Shilling"),
    VND("Vietnamese Dong"),
    XAU("Gold Ounce"),
    AUD("Australian Dollar"),
    ILS("Israeli New Sheqel"),
    GHS("Ghanaian Cedi"),
    GYD("Guyanaese Dollar"),
    KPW("North Korean Won"),
    BOB("Bolivian Boliviano"),
    KHR("Cambodian Riel"),
    MDL("Moldovan Leu"),
    IDR("Indonesian Rupiah"),
    KYD("Cayman Islands Dollar"),
    AMD("Armenian Dram"),
    BWP("Botswanan Pula"),
    SHP("Saint Helena Pound"),
    TRY("Turkish Lira"),
    LBP("Lebanese Pound"),
    TJS("Tajikistani Somoni"),
    JOD("Jordanian Dinar"),
    AED("United Arab Emirates Dirham"),
    HKD("Hong Kong Dollar"),
    RWF("Rwandan Franc"),
    EUR("Euro"),
    LSL("Lesotho Loti"),
    DKK("Danish Krone"),
    CAD("Canadian Dollar"),
    BGN("Bulgarian Lev"),
    MMK("Myanma Kyat"),
    MUR("Mauritian Rupee"),
    NOK("Norwegian Krone"),
    SYP("Syrian Pound"),
    IMP("Manx pound"),
    ZWL("Zimbabwean Dollar"),
    GIP("Gibraltar Pound"),
    RON("Romanian Leu"),
    LKR("Sri Lankan Rupee"),
    NGN("Nigerian Naira"),
    CRC("Costa Rican Colón"),
    CZK("Czech Republic Koruna"),
    PKR("Pakistani Rupee"),
    XCD("East Caribbean Dollar"),
    ANG("Netherlands Antillean Guilder"),
    HTG("Haitian Gourde"),
    BHD("Bahraini Dinar"),
    KZT("Kazakhstani Tenge"),
    SRD("Surinamese Dollar"),
    SZL("Swazi Lilangeni"),
    SAR("Saudi Riyal"),
    TTD("Trinidad and Tobago Dollar"),
    YER("Yemeni Rial"),
    MVR("Maldivian Rufiyaa"),
    AFN("Afghan Afghani"),
    INR("Indian Rupee"),
    AWG("Aruban Florin"),
    KRW("South Korean Won"),
    NPR("Nepalese Rupee"),
    JPY("Japanese Yen"),
    MNT("Mongolian Tugrik"),
    AOA("Angolan Kwanza"),
    PLN("Polish Zloty"),
    GBP("British Pound Sterling"),
    SBD("Solomon Islands Dollar"),
    BYN("Belarusian Ruble"),
    HUF("Hungarian Forint"),
    BIF("Burundian Franc"),
    MWK("Malawian Kwacha"),
    MGA("Malagasy Ariary"),
    XDR("Special Drawing Rights"),
    BZD("Belize Dollar"),
    BAM("Bosnia-Herzegovina Convertible Mark"),
    EGP("Egyptian Pound"),
    MOP("Macanese Pataca"),
    NAD("Namibian Dollar"),
    SSP("South Sudanese Pound"),
    NIO("Nicaraguan Córdoba"),
    PEN("Peruvian Nuevo Sol"),
    NZD("New Zealand Dollar"),
    WST("Samoan Tala"),
    TMT("Turkmenistani Manat"),
    CLF("Chilean Unit of Account (UF)"),
    BRL("Brazilian Real");

    @Getter private final String fullName;
}
